import { Ref } from "react";

const admin = require("firebase-admin");
const serviceAccount = require("./path/to/service-account-file.json"); // Adjust path as necessary

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://southernrealms-f130b-default-rtdb.firebaseio.com/", // Your Realtime Database URL
});

const db = admin.database();

class DBUtil {

  public baseRef: Ref
  constructor(basePath: string) {
    this.baseRef = db.ref(basePath);
  }

  // Create or update data
  set(path, data) {
    return this.baseRef
      .child(path)
      .set(data)
      .then(() => console.log("Data set successfully"))
      .catch((error) => console.error("Error setting data:", error));
  }

  // Retrieve data
  get(path) {
    return this.baseRef
      .child(path)
      .once("value")
      .then((snapshot) => snapshot.val())
      .catch((error) => console.error("Error getting data:", error));
  }

  // Update data
  update(path, data) {
    return this.baseRef
      .child(path)
      .update(data)
      .then(() => console.log("Data updated successfully"))
      .catch((error) => console.error("Error updating data:", error));
  }

  // Delete data
  remove(path) {
    return this.baseRef
      .child(path)
      .remove()
      .then(() => console.log("Data removed successfully"))
      .catch((error) => console.error("Error removing data:", error));
  }

  // Push data with a unique key generated by Firebase
  push(path, data) {
    return this.baseRef
      .child(path)
      .push(data)
      .then((result) => result.key)
      .catch((error) => console.error("Error pushing data:", error));
  }
}

module.exports = DBUtil;
